const dirs = require('./directories.json');

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 博客介绍
  blogIntro: [
    {
      type: 'doc',
      id: 'intro',
      label: '博客介绍',
    },
  ],

  // STM32 知识库（主导航：基础知识 + 外设驱动 + 项目实战）
  [dirs.stm32.dir]: [
    {
      type: 'category',
      label: '基础知识',
      link: { type: 'doc', id: 'stm32/stm32-basics/intro' },
      items: [{ type: 'autogenerated', dirName: 'stm32/stm32-basics' }],
    },
    {
      type: 'category',
      label: '外设驱动',
      link: { type: 'doc', id: 'stm32/stm32-peripherals/intro' },
      items: [{ type: 'autogenerated', dirName: 'stm32/stm32-peripherals' }],
    },
    {
      type: 'category',
      label: '项目实战',
      link: { type: 'doc', id: 'stm32/stm32-projects/intro' },
      items: [{ type: 'autogenerated', dirName: 'stm32/stm32-projects' }],
    },
  ],

  // ESP32 知识库
  [dirs.esp32.dir]: [
    { type: 'autogenerated', dirName: 'esp32' },
  ],

  // 干货分享
  [dirs.sharing.dir]: [
    { type: 'autogenerated', dirName: dirs.sharing.dir },
  ],

  // 行业动态
  [dirs.industry.dir]: [
    { type: 'autogenerated', dirName: dirs.industry.dir },
  ],

  // 开发工具
  [dirs.tools.dir]: [
    { type: 'autogenerated', dirName: dirs.tools.dir },
  ],

  // 科研团队
  [dirs.team.dir]: [
    { type: 'autogenerated', dirName: dirs.team.dir },
  ],
};

module.exports = sidebars;
