/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  blogIntro: [
    {
      type: 'doc',
      id: 'intro',
      label: '博客介绍',
    },
  ],
  stm32: [
    {
      type: 'category',
      label: 'STM32知识库',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '基础知识',
          items: ['stm32/stm32-basics/intro'],
        },
        {
          type: 'category',
          label: '外设驱动',
          items: ['stm32/stm32-peripherals/intro'],
        },
        {
          type: 'category',
          label: '项目实战',
          items: ['stm32/stm32-projects/intro'],
        },
      ],
    },
  ],
  esp32: [
    {
      type: 'category',
      label: 'ESP32知识库',
      collapsed: false,
      items: [
        'esp32/esp32-intro',
        {
          type: 'category',
          label: '项目实战',
          items: ['esp32/esp32-smart-car', 'esp32/esp32-gimbal'],
        },
        {
          type: 'category',
          label: '电赛经验',
          items: ['esp32/esp32-competition-guide'],
        },
      ],
    },
  ],
  sharing: [
    {
      type: 'category',
      label: '干货分享',
      collapsed: false,
      items: [
        'sharing/intro',
        {
          type: 'category',
          label: '笔记文章',
          items: [
            'sharing/git-local-github',
            'sharing/windows-docker',
          ],
        },
      ],
    },
  ],
  industry: [
    {
      type: 'category',
      label: '行业动态',
      collapsed: false,
      items: ['industry/news/intro'],
    },
  ],
  team: [
    {
      type: 'autogenerated',
      dirName: 'team',
    },
  ],
};

module.exports = sidebars;
